# Generated by Django 3.2.18 on 2023-09-18 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produced_energy', models.IntegerField(null=True)),
                ('consumed_energy', models.IntegerField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hash', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('txId', models.CharField(blank=True, default=None, max_length=66, null=True)),
            ],
        ),
    ]
